### ISSUE TITLE
#1 Primeiro Commit - Tarefa 1

### ISSUE THREAD

**Issue by clovesrocha** [clovesrocha/engenharia_software#2]
1. Escreva um código HTML, Hello Word!
2. Faça um commit neste repositório.
3. Print ou colocar o link no Trello.

**Comment by leonardofabiooo** [comment]
oi

**Comment by luiisteo** [comment]
hello word!

**Comment by clovesrocha** [comment]
Acesso ao replit: https://replit.com/join/wkascnufri-profclovesclove
